config/routes.rb
Rails.application.routes.draw do

  resources :users
  #resources :replies

  #resources :posts do
  #  resources :comments
  #end

  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :replies
  end
  resources  :replies

  root to: 'posts#index'

  #route  get 'pages/home'
  get '/pages/about'
  get '/pages/home'




#  post '/comments/:comment_id/replies(.:format)', to 'replies#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  validates :content, presence: true
  validates :comment_id, presence: true
  validates :user_id, presence: true
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_comment_and_reply, :only=> [:edit, :update, :destroy]

#afer creating a repply for a comment, it will show Post for that comment/reply

<<<<<<< Updated upstream
  def create
  #  @reply= @comment.replies.create(reply_params)
=======
  def update
    set_reply
    @reply.update(reply_params)

    c=Comment.find(params[:reply][:comment_id])
    post=Post.find(c.post_id)
    redirect_to post_path(post.id)

    #post=Post.find_by(comment_id=params[:id])
  #  redirect_to post_path(post.id)
  end

  def destroy #reply
    set_reply
    @reply.destroy
    #c=Comment.find(params[:reply][:comment_id])
    post=Post.find_by(comment_id=params[:id])
    redirect_to post_path(post.id)
  end

  def create #reply
>>>>>>> Stashed changes
    @reply=Reply.new(reply_params)
    if @reply.save #if this returns not nill values, then it is success
      flash.notice = "The reply was created successfully."
    else
      flash.now.alert = @reply.errors.full_messages.to_sentence
    end
    redirect_to @comment
  end

  def edit
  end

  def update
    @reply.update(reply_params)
    redirect_to @comment
  end

  def destroy
    @reply.destroy
    redirect_to @comment
  end

  private

  def  set_comment_and_reply
      #comment = params [:reply:comment_id]
      cid=params[:reply][:comment_id].to_i
      if (params[:reply][:id])  #test for nil?
        @reply = Reply.find((params[:reply][:id]).to_i)
      end
    @comment=Comment.find(cid)

  end

  def reply_params
    #params.require(:reply).permit(:comment_id, :user_id, :content)
    #params.require(:reply).permit([:reply][:comment_id], [:reply][:user_id], [:reply][:content])
    cid=(params[:reply][:comment_id]).to_i
    params.require(:reply).permit(params[:reply][:comment_id].to_i, params[:reply][:user_id].to_i, params[:reply][:content])
  end

  def catch_not_found(e)
    Rails.logger.debug("We had a not found exception.")
    flash.alert = e.to_s
    redirect_to posts_path
  end

end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<!--#Prints all replies for one comment -->
<%= form_for [@comment, reply] do |f| %>
<<<<<<< Updated upstream
<div class="row">
  <div class="col-sm">
    <div class="field">
      <%= f.label :user %>
      <%= f.collection_select :user_id, User.all, :id, :name, include_blank: true %>
    </div>
  </div>
  <div class="col-sm">
  <div class="field">
    <%= f.label :content, "Reply" %>
    <%= f.text_field "content" %>
  </div>
  </div>
  <div class="col-sm">
  <div class="field">
    <%= f.label :comment_id %>
    <%= f.text_field :comment_id %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>
=======
  <div class="container  font-weight-lighter">
    <div class="row   text-success ">
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3 text-sm-center p-3 mb-2">
        <%= f.label :user %>:
        <%= f.collection_select :user_id, User.all, :id, :name, include_blank: true %>
      </div>
      <div class="  col-sm-5 text-sm text-wrap">
        <!--<div class="col-sm-6  border text-success border-success rounded-pill border"> -->
        <div class="field" style="display: none;" >
          <%= f.label :content %>
        </div>
        <div class="field" style="padding-top: 15px;" >
          <%= f.text_field "content",  size:"40",border:"none", outline: "none", apperance:"none", placeholder: "Write another reply" %>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="field" style="display: none;" >
          <%= f.label :comment_id %>
          <%= f.text_field :comment_id %>
        </div>
        <div class="actions" style="padding-top: 15px;">
          <%= f.submit %>
          <!--  <button type="button" class="btn btn-sm btn-light btn-outline-secondary" onclick="window.history.back();">Cancel</button> -->
        </div>
      </div>
    </div>
  </div>
<% end %>


<!--  REPLIES FORM -->
>>>>>>> Stashed changes

app/views/replies/_reply.html.erb
<<<<<<< Updated upstream
<div>
  <strong><%= reply.user.name %> replays:</strong> <!-- reply.comment.user.name -->
    <%= reply.content%>

    <div class="comment-admin">
      <!--<#%= link_to "Edit", edit_comment_reply_path(@comment, reply) %>-->
      <%= @comment=Comment.find(reply.comment_id)%>
      <%= link_to "Edit", edit_reply_path(@comment, reply) %>
      <%= link_to "Delete", [@comment, reply], method: :delete  %>
      </div>
=======
<div class="container text-sm-left">
  <div class="row   text-success font-weight-lighter  rounded-lg ">
    <div class="col-sm-2  text-sm-right ">
      <strong>
        <%= reply.user.name %> replied:
      </strong> <!-- reply.comment.user.name -->
    </div>
    <div class="col-sm-6 text-wrap bg-light border  border-white rounded-pill border-left-0">
      <%= reply.content %>
    </div>
    <div class="comment-admin col-sm-4">
      <!--<#%= link_to "Edit", edit_comment_reply_path(@comment, reply) %>-->
      <% @comment=Comment.find(reply.comment_id)%>
      <%= link_to "Edit | ", edit_comment_reply_path(@comment, reply) %>
      <%= link_to "Delete ", [@comment, reply], method: :delete  %>
    </div>
  </div>
  <div class="row ">
  </div>
>>>>>>> Stashed changes
</div>

app/views/replies/edit.html.erb
<h1>Edit Reply</h1>
<%= render partial: "form", locals: {reply: @reply} %>