config/routes.rb
Rails.application.routes.draw do

  resources :users
  #resources :replies

  #resources :posts do
  #  resources :comments
  #end

  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :replies
  end
  resources  :replies

  root to: 'posts#index'

  #route  get 'pages/home'
  get '/pages/about'
  get '/pages/home'




#  post '/comments/:comment_id/replies(.:format)', to 'replies#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :replies, dependent: :destroy
  belongs_to :user

  validates :content, presence: true



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_post,  :set_comment, :only =>[:edit, :update, :destroy]#except: [:create]

  def create
    byebug
    @post=Post.find(params[:comment][:post_id])
    @comment= @post.comments.create(comment_params)
    if @reply.save #if this returns not nill values, then it is success
      flash.notice = "The reply was created successfully."
      redirect_to @post
    else
      flash.now.alert = @reply.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    @comment.update(comment_params)
    redirect_to @post
  end

  def destroy
    @comment.destroy
    redirect_to @post
  end


  def  set_post
      @post=Post.find(params[:comment][:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end

  def catch_not_found(e)
    Rails.logger.debug("We had a not found exception.")
    flash.alert = e.to_s
    redirect_to posts_path
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!--Displays comments for that post it was called from -->
<<<<<<< Updated upstream
<div>
  <div>
    <h4>
      <strong>  <%= comment.user.name %>  </strong>
      says:
    </h4>
    <%= comment.content %>
=======
<div class="container  font-weight-lighter border-info rounded-lg border">
  <div class="row  border text-warning rounded-lg border">
    <div class="col-sm-2 text-wrap">
      <h6> <strong>  <%= comment.user.name %>  </strong> said:  </h6>
    </div>
    <div class="col-sm-7 text-wrap text-sm-left">
      <%= comment.content %>
    </div>
    <div class="col-sm-3 text-wrap">
      <%= link_to "Edit ", edit_post_comment_path(@post, comment) %> -
      <%= link_to "Delete Comment", [@post, comment], method: :delete  %>
    </div>
>>>>>>> Stashed changes
  </div>

    <!-- if this post has comments, it will display them -->
<<<<<<< Updated upstream
  <% if comment.replies.present? %>
    <div id="replies">
      <h4>Replies to this comment:</h4>
      <!-- The `comments` method returns an array-like collection, so we can call `each` on it: -->
      <%= render comment.replies %>
    </div>
  <% end %>

  <div class="container">
    <h4> Reply </h4>
    <%= render :partial => "replies/form", locals: {reply: comment.replies.new} %>
  </div>
    <div class="comment-admin">
      <!-- <#%= link_to "Edit", edit_post_comments_path(@post, comment) %> -->
      <!--<#%= link_to "Reply", new_reply_path(@comment, comment.id) %> -->

      <%= link_to "Edit", edit_post_comment_path(@post, comment) %>
      <%= link_to "Delete", [@post, comment], method: :delete  %>
=======
  <div class="row  border text-warning border-warning rounded-lg border">
    <div class="col-sm-12">
      <% if comment.replies.present? %>
        <div id="replies">
          <!-- The `comments` method returns an array-like collection, so we can call `each` on it: -->
          <%= render comment.replies %>
        </div>
      <% end %>
      </div>
    </div>
    <div class="row  border text-warning border-warning rounded-lg border">
      <div class="col-sm-12">
          <div class="container">
            <%= render :partial => "replies/form", locals: {reply: comment.replies.new} %>
          </div>
        </div>
>>>>>>> Stashed changes
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<!--#Prints all comments for one post , called for EDIT-->
<%= form_for [@post, comment] do |f| %>

    <div class="row  border text-success font-weight-lighter border-warning rounded-lg border  text-sm-">
      <div class=" col-sm-2">
      </div>
      <div class="field col-sm-2 text-sm text-wrap" style="padding-top: 15px;">
        <%= f.label :user %>
        <%= f.collection_select :user_id, User.all, :id, :name, include_blank: true %>
      </div>

<<<<<<< Updated upstream
  <div class="field">
    <%= f.label :content, "Comment" %>
    <%= f.text_area "content" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
=======
      <div class="field  col-sm-5 text-sm text-wrap" style="padding-top: 15px;">
        <div class="field" style="display:none">
          <%= f.label :content, "Comment" %>
        </div>
        <%= f.text_area "content", size:"40", placeholder: "Write another comment to this post"  %>
      </div>

      <div class="actions field col-sm-1 text-sm-center" style="padding-top: 15px;">
        <%= f.submit %>
        </div>
        <div class=" col-sm-2">
        </div>
    </div>

>>>>>>> Stashed changes
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render partial: "form", locals: {comment: @comment} %>