config/routes.rb
Rails.application.routes.draw do

  resources :users
  #resources :replies

  #resources :posts do
  #  resources :comments
  #end

  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :replies
  end
  resources  :replies

  root to: 'posts#index'

  #route  get 'pages/home'
  get '/pages/about'
  get '/pages/home'




#  post '/comments/:comment_id/replies(.:format)', to 'replies#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  has_many :Posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout 'user_layout' #this will check for flash alerts

  def index
    @users = User.all
    render template: "users/index.html.erb"
  end

  def new
    @user=User.new
  end

  def create
    #@user= User.new(params[:user])
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You signed up successfully!"
      flash[:color] = "valid"
      #redirect_to @user\
      render :show
    else
      flash[:notice] = " user or password was not correct. Please try again"
      flash[:color] = "invalid"
      render :new
    end
    #render :new
  end

  def edit
  end
  def update
    if @user.update(user_params) #if this returns not nill values, then it is success
      flash.notice = "The user record was created successfully."
      redirect_to @user
    else
      flash.now.alert =@user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def show
  end

  def destroy
    @user.destroy
    flash.notice = "The user record was erased successfully."
    redirect_to users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a lists of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to users_path
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password%>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit My User Account</h1>

<%= render partial: 'form',  locals: {user: @user} %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   <link rel="stylesheet" href="stylesheets/pages.scss" >
    <title>Welcome to the Community Mural Portal!</title>
  </head>
  <body  id="home" data-spy="scroll" data-target=".navbar" data-offset="100" class="">
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-success fixed-top">
      <div class="container" >
      <a class="navbar-brand order-1 mr-0" href="https://www.codethedream.org" target="_blank">Presented by Code The Dream</a>
        <%= image_tag("CTD_Logo_Primary-2.png", border: 0, style:'width:10%') %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">

            <a class="nav-item nav-link" href="#about">About</a>
            <a class="nav-item nav-link" href="users#index"> Users </a>
            <a class="nav-item nav-link" href="posts#new"> Create Post </a>
            <a class="nav-item nav-link" href="posts#index"> Home </a>
          </div>
        </div>
      </div>
    </nav>
<br><br>
<p id="notice"><%= notice %></p> 

<h1>Mural past Visitors</h1>

<table>
  <thead>
    <tr>
      <th> Name</th>
      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<div class="btn-group mt-4" role="group" aria-label="Callout buttons">
  <a class="btn btn-light btn-lg" href="posts#index" > Back to Posts</a>
</div>

  <div class="btn-group mt-4" role="group" aria-label="Callout buttons">
    <a class="btn btn-light btn-lg" href="<%= new_user_path %>" > Create user</a>
  </div>
<!-- <#!%= link_to 'Home', 'home#index' %> | -->
</body>
</html>

app/views/users/login.html.erb
<p id="notice"><%= notice %></p>

<h1>Login Page</h1>

<table>
  <thead>
    <tr>
      <th>name:</th>
      <th>email:</th>
      <th>password:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1> <%= t 'sign_up'%></h1>

  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <p> User Name:</br> <%= f.text_field :name%> </p>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup %>
    <button type="button" class="btn btn-primary" onclick="window.history.back();">Cancel</button>
  <% end %>

  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
#shows the comments each user has made for each post of mural


<p id="notice"><%= notice %></p>
<p>
  <strong>User name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>

  <!-- The `comments` method returns an array-like collection, so we can call `each` on it: -->
  <!--<#%= render :partial => "books/form", locals: {book: @user.books.new} %> -->


<%= link_to 'Edit my profile', edit_user_path(@user) %>
<%= link_to "Go to  All Posts", posts_path %>
<%= link_to 'Back', users_path %>

app/views/users/signup.html.erb
signup form